### ISSUE TITLE
您好，数据集不能下载的问题

### ISSUE THREAD

**Issue by PROCESSgg** [wanpingDou/KDD_Cup2020_Debiasing#1]
天池报名截止了，数据无法下载，请问怎么样才能获得数据呢？

**Comment by wanpingDou** [comment]
我有数据，我可以整理一下发给你，毕竟数据量太大了，需要压缩

**Comment by wanpingDou** [comment]
> 天池报名截止了，数据无法下载，请问怎么样才能获得数据呢？

我有数据，我可以整理一下发给你，毕竟数据量太大了，需要压缩一下。

**Comment by PROCESSgg** [comment]
非常感谢大佬，麻烦整理完发我邮箱如何:) 1206498387@qq.com，再次感谢！

**Comment by wanpingDou** [comment]
> 非常感谢大佬，麻烦整理完发我邮箱如何:) [1206498387@qq.com](mailto:1206498387@qq.com)，再次感谢！

完全没问题，等我整理好M5，和KDD最近就会有内容发出

**Comment by PROCESSgg** [comment]
好嘞。

**Comment by wanpingDou** [comment]
> 好嘞。

数据已经列出，这个是官方的链接，抓紧下载。步骤如下：

- data文件夹下`debiasing_data_20200401.csv`，点击链接并下载数据。
- 并在同一路径下找到`[Official]含解压密码.md `文件，打开并找到对应的密码解压数据。
